main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from polls import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('auth/', include('auth_login.urls')),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

                          
        

polls/urls.py
from django.urls import path 
from polls import views

app_name = 'polls'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('partidos/', views.Partido_list, name='Partido_list'),
    path('teams/', views.Team_list, name='Team_list'),
    path('players/', views.Player_list, name='Player_list'),
    path('playercreate/', views.playercreate, name='playercreate'),
    path('playerupdate/<int:pk>', views.playerupdate, name='playerupdate'),
    path('coachs/', views.Coach_list, name='Coach_list'),
    path('coachdelete/<int:pk>', views.coachdelete, name='coachdelete'),
    path('coachcreate/', views.coachcreate, name='coachcreate'),
    path('coachupdate/<int:pk>', views.coachupdate, name='coachupdate'),
    path('last5/', views.Last5_list, name='Last5_list'),
    path('createTeam/', views.createTeam, name='createTeam'),
    path('teamupdate/<int:pk>', views.teamupdate, name='teamupdate'),
    path('teamdelete/<int:pk>', views.teamdelete, name='teamdelete'),
    path('playerdelete/<int:pk>', views.playerdelete, name='playerdelete'),
]

polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Coach(models.Model):

    
    Nombre_Coach = models.CharField(max_length=200,blank=True ,null=True)
    Edad_Coach = models.PositiveIntegerField(blank=True ,null=True) 
    Email_Coach = models.EmailField(max_length=200, blank=True ,null=True)
    Rut_Coach = models.CharField(max_length=200, blank=True ,null=True)
    Apodo_Coach = models.CharField(max_length=200, blank=True ,null=True)
    user_Coach = models.OneToOneField(User, blank=True ,null=True, on_delete=models.CASCADE)
    created_date = models.DateTimeField('date created', default=timezone.now)
    

    def __str__(self):
        return str(self.Nombre_Coach)

class Team(models.Model):
    Nombre_Team = models.CharField(max_length=200)
    Descripcion_Team = models.TextField()
    Logo_Team = models.ImageField(upload_to= "Fotos_Team/",blank=True, null=True)
    Code_Team = models.CharField(max_length=20,unique=True)
    Coach_Team = models.OneToOneField(Coach, on_delete=models.CASCADE)

    def __str__(self):
        return self.Code_Team

POSICION_PLAYER = (
    ('BA', 'Base'),
    ('ES', 'Escolta'),
    ('AL', 'Alero'),
    ('AP', 'Ala-pivot'),
    ('PI', 'Pivot'),
)

class Player(models.Model):
    Nombre_Player = models.CharField(max_length=200)
    Apodo_Player = models.CharField(max_length=200)
    Nacimiento_Player = models.DateField()
    Edad_Player =models.PositiveIntegerField()
    Rut_Player = models.CharField(max_length=12)
    Email_Player = models.EmailField()
    Estatura_Player = models.PositiveIntegerField(help_text='Altura en cm')
    Peso_Player = models.PositiveIntegerField(help_text='En gramos')
    Foto_Player = models.ImageField(upload_to= "Fotos_Player/",blank=True, null=True)
    Posicion_Player = models.CharField(choices=POSICION_PLAYER, max_length=2)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    created_date = models.DateTimeField('date created', default=timezone.now)

    def __str__(self):
        return '{Nombre_Player} ({team})'. format(Nombre_Player=self.Nombre_Player, team=self.team)
    



class Roster(models.Model):
    name = models.CharField(max_length=150)
    player = models.ManyToManyField(Player)

    def __str__(self):
        return self.name

class Partido(models.Model):
    Nombre_Partido = models.CharField(max_length=200)
    team1 = models.ForeignKey(Roster,related_name='team1', on_delete=models.CASCADE)
    team2 = models.ForeignKey(Roster,related_name='team2', on_delete=models.CASCADE)
    fecha = models.DateField()
    created_date = models.DateTimeField('date created', default=timezone.now)
    def __str__(self):
        return '{name} ({team1} vs {team2})'.format(
            name=self.Nombre_Partido,
            team1=self.team1,
            team2=self.team2

        )

polls/forms.py
from django import forms
from polls.models import Team,Player,Coach

class TeamForm(forms.ModelForm):
    class Meta:
        model= Team
        fields = '__all__'

class PlayerForm(forms.ModelForm):
    class Meta:
        model= Player
        fields = '__all__'

class CoachForm(forms.ModelForm):
    class Meta:
        model= Coach
        fields = '__all__'

polls/views.py
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render, redirect
from polls.models import Team, Player , Partido, Coach 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from polls.forms import TeamForm,PlayerForm, CoachForm
from django.contrib.auth.decorators import login_required , permission_required 
from django.contrib import messages
from django.contrib.auth.models import User


@login_required
def home(request):
    template_name = 'home.html'
    data = {}
    SU=request.user.is_superuser
    if SU==True:
        data ['match'] = Partido.objects.all().order_by('created_date').reverse()[:3]
        data ['players'] = Player.objects.all().order_by('created_date').reverse()[:3]  
        data ['coachs'] = Coach.objects.all().order_by('created_date').reverse()[:3]
    else :
        data ['players'] = Player.objects.all().order_by('created_date').reverse()[:3]
        data ['match'] = Partido.objects.all().order_by('created_date').reverse()[:3] 

    return render(request, template_name, data)
@login_required
def Team_list(request):
    template_name ='Team_list.html'
    data={}
    print("User login:", request.user )
    data['title'] ='List Teams'
    tm= Team.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(tm, 1)
    try:
        data['Team'] = paginator.page(page)
    except PageNotAnInteger:
        data['Team'] = paginator.page(1)
    except EmptyPage:
        data['Team'] = paginator.page(paginator.num_pages)
    return render(request, template_name, data)
@login_required
def Player_list(request):
    template_name = 'Player_list.html'
    data = {}
    data ['title']= 'List Players'
    data ['players'] = Player.objects.all().order_by('team')
    data ['teams']= Team.objects.all().order_by('Nombre_Team')
    tm= Team.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(tm, 1)
    try:
        data['teams'] = paginator.page(page)
    except PageNotAnInteger:
        data['teams'] = paginator.page(1)
    except EmptyPage:
        data['teams'] = paginator.page(paginator.num_pages)
    return render(request, template_name, data)
    

@login_required
def Coach_list(request):
    template_name = 'Coach_list.html'
    data = {}
    data ['title']= 'List Coach'
    data['coachs'] = Coach.objects.all()
    
    tm= Coach.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(tm, 1)
    try:
        data['coachs'] = paginator.page(page)
    except PageNotAnInteger:
        data['coachs'] = paginator.page(1)
    except EmptyPage:
        data['coachs'] = paginator.page(paginator.num_pages)
    return render(request, template_name, data)
    
@login_required
def Partido_list(request):
    template_name = 'Partido_list.html'
    data = {}
    data ['title']= 'List Partido'
    data ['match'] = Partido.objects.all()
    return render(request, template_name, data)
@login_required
def Last5_list(request):
    template_name = 'Partido_list.html'
    data = {}
    data ['title']= 'List Partido'
    data ['match'] = Partido.objects.all().order_by('created_date').reverse()[:5]
    return render(request, template_name, data)
@permission_required('polls.createTeam')    
def createTeam (request):
    data = {}
    template_name ='createTeam.html'
    data['form'] = TeamForm(request.POST or None)
    if data['form'].is_valid():
        data['form'].save()
        messages.add_message(request, messages.SUCCESS, 'Equipo guardado correctamente')
        return redirect('polls:Team_list')
        
    return render(request, template_name, data)
@permission_required('polls.teamupdate') 
def teamupdate (request,pk):
    data = {}
    template_name ='teamupdate.html'
    team = Team.objects.get(pk=pk)
    data['form'] = TeamForm(request.POST or None, instance=team)
    if data['form'].is_valid():
        data['form'].save()
        messages.add_message(request, messages.SUCCESS, 'Equipo guardado correctamente')
        return redirect('polls:Team_list')
    return render(request, template_name,data)
@permission_required('polls.teamdelete')
def teamdelete(request,pk):
    data = {}
    template_name = 'teamdelete.html'
    data['team'] = Team.objects.get(pk=pk)
    if request.method =='POST':
        data['team'].delete()
        messages.add_message(request, messages.ERROR, 'Equipo ELIMINADO correctamente')
        return redirect('polls:Team_list')
    return render(request, template_name,data)
@permission_required('polls.playercreate')
def playercreate(request):
    data = {}
    template_name ='playercreate.html'
    data['form'] = PlayerForm(request.POST or None)
    if data['form'].is_valid():
        data['form'].save()
        messages.add_message(request, messages.SUCCESS, 'Player guardado correctamente')
        return redirect('polls:Player_list')
        
    return render(request, template_name, data)
@permission_required('polls.playerupdate')
def playerupdate (request,pk):
    data = {}
    template_name ='playerupdate.html'
    player = Player.objects.get(pk=pk)
    data['form'] = PlayerForm(request.POST or None, instance=player)
    if data['form'].is_valid():
        data['form'].save()
        messages.add_message(request, messages.SUCCESS, 'Player guardado correctamente')
        return redirect('polls:Player_list')
    return render(request, template_name,data)
@permission_required('polls.playerdelete')
def playerdelete(request,pk):
    data = {}
    template_name = 'playerdelete.html'
    data['player'] = Player.objects.get(pk=pk)
    if request.method =='POST':
        data['player'].delete()
        messages.add_message(request, messages.ERROR, 'Player eliminado correctamente')
        return redirect('polls:Player_list')
    return render(request, template_name,data)

@permission_required('polls.coachcreate')
def coachcreate(request):
    data = {}
    template_name ='coachcreate.html'
    data['form'] = CoachForm(request.POST or None)
    if data['form'].is_valid():
        data['form'].save()
        return redirect('polls:Coach_list')
        
    return render(request, template_name, data)
@permission_required('polls.change_coach',login_url='/auth/login')
def coachupdate (request,pk):
    data = {}
    template_name ='coachupdate.html'
    coachs = Coach.objects.get(pk=pk)
    data['form'] = CoachForm(request.POST or None, instance=coachs)
    if data['form'].is_valid():
        data['form'].save()
        return redirect('polls:Coach_list')
    return render(request, template_name,data)
@permission_required('polls.coachdelete')
def coachdelete(request,pk):
    data = {}
    template_name = 'coachdelete.html'
    data['coach'] = Coach.objects.get(pk=pk)
    if request.method =='POST':
        data['coach'].delete()
        return redirect('polls:Coach_list')
    return render(request, template_name,data)

polls/templates/Coach_list.html
{% extends "base.html" %}
{% block title %}Coachlist{% endblock %}
{%block content%}
<div class="row mt-2">
    <div class="col- md-9 col-lg-9 ">
        <h1>{{title}}</h1>          
    </div>
    <div class="col-md-3 col-lg-3 ">
        {% if perms.polls.add_coach %}
        <a href="{% url 'polls:coachcreate' %}" class="btn btn-success btn-block mt-2"><i class="fas fa-plus-square"></i> | Agregar Coach</a> 
        {% endif %}
    </div>
</div>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'polls:home' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'polls:Coach_list' %}" >Coachs</a></li>
      
    </ol>
  </nav>

<div class="row">
    <div class="col">
        <table class="table table-striped table-hover mt-5">
            <thead>
                <tr>
                <th>Nombre Team</th>
                <th>Coach</th>
                <th>Opciones</th>
                </tr>
            </thead>
            {% for coach in coachs %}
                <tr>
                    <td>{{coach.team.Nombre_Team }}</td>
                    <td>{{coach.Nombre_Coach}}</td>
                    <td>
                        {% if user.is_superuser or user.coach.Nombre_Coach == coach.Nombre_Coach  %}
                            <a href= "{% url 'polls:coachupdate' coach.pk %}"><i class="fas fa-edit"></i></a> |
                        {% endif %}
                        {% if user.is_superuser %}
                            <a href= "{% url 'polls:coachdelete' coach.pk %}"><i class="fas fa-trash"></i></a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
            {% if coachs.has_other_pages %}
                <nav aria-label="Page navigation"></nav>
                    <ul class="pagination">
                        {% if coachs.has_previous %}
                            <li class="page-item"><a href="?page={{ coachs.previous_page_number }}" class="page-link">&laquo;</a></li>
                        {% else %}
                            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                        {% endif %}
                        {% for i in coachs.paginator.page_range %}
                            {% if coachs.number == i %}
                                <li class="page-item active"><span class="page-link" >{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if coachs.has_next %}
                            <li class="page-item"><a  href="?page={{ coachs.next_page_number }}" class="page-link">&raquo;</a></li>
                        {% else %}
                            <li class="page-item" class="disabled"><span class="page-link">&raquo;</span></li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>       
    </div>
</div>

{% endblock %}

polls/templates/Last5_list.html
<!DOCTYPE html>
<html lang = 'en'>
<head>
    <meta charset="UTF-8">
    <title>MATCH</title>>
</head>>
<body>
    
    <h1>{{title}}</h1>
    
    <table style="width:100%" border="5">
     <tr>
        <th>Nombre Partido</th>
        <th>Equipo 1</th>
        <th>Equipo 2</th>
        <th>Fecha</th>
       
     </tr>
     {% for partido in match %}
     <tr>
        <td>{{partido.Nombre_Partido}}</td>
        <td>{{partido.team1}}</td>
        <td>{{partido.team2}}</td>
        <td>{{partido.fecha}}</td>
        
     </tr>
     {% endfor %}
    </table>
    
</body>
</html>>

polls/templates/Team_list.html
{% extends "base.html" %}
{% block title %}Teamlist{% endblock %}
{%block content%}
<div class="row mt-2">
    <div class="col- md-9 col-lg-9 ">
        <h1>{{title}}</h1>          
    </div>
    <div class="col-md-3 col-lg-3 ">
        {% if perms.polls.add_team %}
        <a href="{% url 'polls:createTeam'%}" class="btn btn-success btn-block mt-2"><i class="fas fa-plus-square"></i> | Agregar Team</a> 
        {% endif %}
    </div>

</div>
<!-- bloque titulo-->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'polls:home' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'polls:Team_list' %}" >Teams</a></li>
    </ol>
  </nav>


<!--bloque table--> 
<div class="row">
    <div class="col">
        {% if messages %}
          {% for message in messages %}
            <div class="alert {{message.tags}} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data.dismiss="alert" arial-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
          {% endfor %}
        {% endif %}
        <table class="table table-striped table-hover mt-5">
            <thead>
                <tr>
                <th>Nombre</th>
                <th>Descripcion</th>
                <th>Logo</th>
                <th>Code</th>
                <th>Coach</th>
                <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
            {% for team in Team %}
        
                <tr>
                    <td>{{team.Nombre_Team}}</td>
                    <td>{{team.Descripcion_Team}}</td>
                    <td>{{team.Logo_Team}}</td>
                    <td>{{team.Code_Team}}</td>
                    <td>{{team.Coach_Team}}</td>
                    <td>
                        {% if perms.polls.change_team %}
                            <a href= "{% url 'polls:teamupdate' team.pk %}"><i class="fas fa-edit"></i></a> |
                        {% endif %}
                        {% if perms.polls.delete_team %}
                            <a href= "{% url 'polls:teamdelete' team.pk %}"><i class="fas fa-trash"></i></a> 
                        {% endif %} 
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
            {% if Team.has_other_pages %}
            <nav aria-label="Page navigation"></nav>
                <ul class="pagination">
                    {% if Team.has_previous %}
                        <li class="page-item"><a href="?page={{ Team.previous_page_number }}" class="page-link">&laquo;</a></li>
                    {% else %}
                        <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                    {% endif %}
                    {% for i in Team.paginator.page_range %}
                        {% if Team.number == i %}
                            <li class="page-item active"><span class="page-link" >{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if Team.has_next %}
                        <li class="page-item"><a  href="?page={{ Team.next_page_number }}" class="page-link">&raquo;</a></li>
                    {% else %}
                        <li class="page-item" class="disabled"><span class="page-link">&raquo;</span></li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
            

        
    </div>
</div> 





{% endblock %}

polls/templates/coachcreate.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
    <h2>Agregar Coach</h2>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item"><a href="{% url 'polls:Coach_list' %}" >Coachs</a></li>
          <li class="breadcrumb-item"><a href="{% url 'polls:coachcreate' %}" >CreateCoach</a></li>
        </ol>
      </nav>
    {% bootstrap_messages %}
    <form class="" method="POST">
        {% csrf_token %}
        
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
            Guardar Coach
            </button>
  {% endbuttons %}

    </form>
{% endblock %}

polls/templates/coachdelete.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
    <h2>Eliminar Coach</h2>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'polls:Coach_list' %}">Coachs</a></li>
        <li class="breadcrumb-item"><a href="" >CoachDelete</a></li>
      </ol>
    {% bootstrap_messages %}
    <p>Estas seguro de eliminar a <strong><a href= "{% url 'polls:coachupdate' coach.pk %}">{{team.Code_Team}}</a>?</strong> </p>
    <form class="" method="POST">
        {% csrf_token %}
        {% buttons %}
        <input type="submit" name="" class="btn btn-danger"  value="Eliminar"> | <a href= "{% url 'polls:Coach_list' %}" class="btn btn-light">Cancelar </a>
    </form>
  {% endbuttons %}

    
{% endblock %}

polls/templates/createTeam.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
    <h2>Agregar Equipo</h2>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item"><a href="{% url 'polls:Team_list' %}" >Teams</a></li>
          <li class="breadcrumb-item"><a href="{% url 'polls:createTeam' %}" >CreateTeam</a></li>
        </ol>
      </nav>
    {% bootstrap_messages %}
    <form class="" method="POST">
        {% csrf_token %}
        
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
            Guardar Team
            </button>
  {% endbuttons %}

    </form>
{% endblock %}

polls/templates/home.html
{% extends "base.html" %}
{% block title %}Teamlist{% endblock %}
{%block content%}

<div class="row mt-2">
    <div class="col- md-9 col-lg-9 ">
        <h1>{{title}}</h1>          
    </div>
</div>

<!-- bloque titulo-->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="">Home</a></li>
    </ol>
</nav>
<!--bloque table--> 
<div class="row">
    <div class="col">
      
        <table class="table table-striped table-hover mt-5">
            <thead>
                <tr>
                <th>Team</th>
                <th>Match</th>
                <th>Player</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><a href= "{% url 'polls:Team_list'%}">Listar Equipos</a></td>
                    <td><a href= "{% url 'polls:Partido_list'%}">Listar Partidos</a></td>
                    <td><a href= "{% url 'polls:Player_list'%}">Listar Jugadores</a></td>
                </tr>
            </tbody>
        </table>
    
    <div class="row mt-1">
        <div class="col- md-5 col-lg-5 ">
            <h1>Ultimos Partidos</h1>          
        </div>
    </div>
       <table class="table table-striped table-hover mt-5">
            <thead>
                <tr>
                <th>Nombre Partido</th>
                <th>Equipo 1</th>
                <th>Equipo 2</th>
                <th>Fecha</th>
                </tr>
            </thead>
            {% for partido in match %}
                <tr>
                <td>{{partido.Nombre_Partido}}</td>
                <td>{{partido.team1}}</td>
                <td>{{partido.team2}}</td>
                <td>{{partido.fecha}}</td>
                </tr>
            {% endfor %}
        </table>
    {% if user.is_superuser %}
        <div class="row mt-1">
            <div class="col- md-5 col-lg-5 ">
                <h1>Ultimos Jugadores</h1>          
            </div>
        </div>

        <table class="table table-striped table-hover mt-5">
            <thead>
                <tr>
                <th>Nombre</th>
                <th>Apodo</th>
                <th>Edad</th>
                <th>Rut</th>
               </tr>
            </thead>
            {%for y in players %}
                
                    <tr>
                        <td>{{y.Nombre_Player}}</a></td>
                        <td>{{y.Apodo_Player}}</td>
                        <td>{{y.Edad_Player}}</td>
                        <td>{{y.Rut_Player}}</td>
                        
                    </tr>
                
            {% endfor %}
        </table> 
        <div class="row mt-1">
            <div class="col- md-5 col-lg-5 ">
                <h1>Ultimos Entrenadores</h1>          
            </div>
        </div>
        
        <table class="table table-striped table-hover mt-5">
                    <thead>
                        <tr>
                        <th>NombreTeam</th>
                        <th>Coach</th>
                        
                        </tr>
                    </thead>
                    {% for coach in coachs %}
                        <tr>
                            <td>{{coach.team.Nombre_Team }}</td>
                            <td>{{coach.Nombre_Coach}}</td>
                            
                        </tr>
                    {% endfor %}
        </table>
    {% endif %}
    {% if user.Coach.Nombre_Coach == Team.Coach_Team %}
        
        
            <div class="row mt-1">
                <div class="col- md-5 col-lg-5 ">
                    <h1>Ultimos Jugadores</h1>          
                </div>
            </div>

            <table class="table table-striped table-hover mt-5">
                <thead>
                    <tr>
                    <th>Nombre</th>
                    <th>Apodo</th>
                    <th>Edad</th>
                    <th>Rut</th>
                    <th>Team</th>
                </tr>
                </thead>
                {%for y in players %}
                    
                        <tr>
                            <td>{{y.Nombre_Player}}</a></td>
                            <td>{{y.Apodo_Player}}</td>
                            <td>{{y.Edad_Player}}</td>
                            <td>{{y.Rut_Player}}</td>
                            <td>{{y.team}}</td>
                            
                        </tr>
                    
                {% endfor %}
            </table> 
    {% endif %}
  
    

   
   
    </div>
</div>


























{% endblock %}

polls/templates/playercreate.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
    <h2>Agregar Jugador</h2>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item"><a href="{% url 'polls:Player_list' %}" >Players</a></li>
          <li class="breadcrumb-item"><a href="{% url 'polls:playercreate' %}" >CreatePlayer</a></li>
        </ol>
      </nav>
    {% bootstrap_messages %}
    <form class="" method="POST">
        {% csrf_token %}
        
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
            Guardar Jugador
            </button>
  {% endbuttons %}

    </form>
{% endblock %}

polls/templates/teamdelete.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
    <h2>Eliminar Equipo</h2>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'polls:Coach_list' %}">Teams</a></li>
        <li class="breadcrumb-item"><a href="" >TeamDelete</a></li>
      </ol>
    {% bootstrap_messages %}
    <p>Estas seguro de eliminar a <strong><a href= "{% url 'polls:teamupdate' team.pk %}">{{team.Code_Team}}</a>?</strong> </p>
    <form class="" method="POST">
        {% csrf_token %}
        {% buttons %}
        <input type="submit" name="" class="btn btn-danger" value="Eliminar"> | <a href= "{% url 'polls:Team_list' %}" class="btn btn-light">Cancelar </a>
    </form>
  {% endbuttons %}

    
{% endblock %}